version: '3.8'
services:
  myapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/memecoins?sslmode=disable
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: